name: Continuous Integration

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [8.1, 8.2, 8.3, 8.4]
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
      - uses: php-actions/phpunit@v4
        with:
          php_version: ${{ matrix.php-versions }}
          configuration: phpunit.xml
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: 8.4
      - uses: php-actions/phpstan@v3
        with:
          php_version: 8.4
          configuration: phpstan.neon
